---
- name: Kubernetes Worker Node Setup
  hosts: nodes
  become: yes

  tasks:
    # Check if already joined
    - name: Check if node is already part of a cluster
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf_check

    # Wait for join command
    - name: Wait for join command file to be created by controller
      wait_for:
        path: /vagrant/kubeconfig/join-command.sh
        state: present
        timeout: 300
      when: not kubelet_conf_check.stat.exists

    # Execute join command
    - name: Read join command from shared folder
      slurp:
        src: /vagrant/kubeconfig/join-command.sh
      register: join_command_content
      when: not kubelet_conf_check.stat.exists

    - name: Join worker node to Kubernetes cluster
      command: "{{ join_command_content.content | b64decode | trim }}"
      when: not kubelet_conf_check.stat.exists
      register: join_output
      async: 600
      poll: 10
      ignore_errors: yes

    - name: Display join output
      debug:
        var: join_output
      when: join_output is defined

    - name: Check if join failed
      debug:
        msg: "Join command failed. Check the output above for errors."
      when: join_output is defined and join_output.rc != 0

    - name: Fail if join was unsuccessful
      fail:
        msg: "kubeadm join failed. Return code: {{ join_output.rc }}. Output: {{ join_output.stdout }}. Error: {{ join_output.stderr }}"
      when: join_output is defined and join_output.rc != 0

    # Verify join
    - name: Verify kubelet.conf was created
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: verify_join

    - name: Confirm node has joined the cluster
      debug:
        msg: "Node successfully joined the Kubernetes cluster"
      when: verify_join.stat.exists
