---
# Source: sms-app/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: sms-app
  labels:
    helm.sh/chart: sms-app-0.1.0
    app.kubernetes.io/name: sms-app
    app.kubernetes.io/instance: sms-app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: sms-app/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sms-app-secret
  namespace: sms-app
  labels:
    helm.sh/chart: sms-app-0.1.0
    app.kubernetes.io/name: sms-app
    app.kubernetes.io/instance: sms-app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  smtp-username: "placeholder-user"
  smtp-password: "placeholder-pass"
---
# Source: sms-app/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sms-app-config
  namespace: sms-app
  labels:
    helm.sh/chart: sms-app-0.1.0
    app.kubernetes.io/name: sms-app
    app.kubernetes.io/instance: sms-app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
data:
  LOG_LEVEL: "INFO"
  FEATURE_FLAG_EXAMPLE: "true"
---
# Source: sms-app/templates/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sms-app-frontend
  namespace: sms-app
  labels:
    helm.sh/chart: sms-app-0.1.0
    app.kubernetes.io/name: sms-app
    app.kubernetes.io/instance: sms-app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    app: frontend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: frontend
    app.kubernetes.io/name: sms-app
    app.kubernetes.io/instance: sms-app
---
# Source: sms-app/templates/model-service-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sms-app-model-service
  namespace: sms-app
  labels:
    helm.sh/chart: sms-app-0.1.0
    app.kubernetes.io/name: sms-app
    app.kubernetes.io/instance: sms-app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    app: model-service
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: model-service
    app.kubernetes.io/name: sms-app
    app.kubernetes.io/instance: sms-app
---
# Source: sms-app/templates/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-app-frontend
  namespace: sms-app
  labels:
    helm.sh/chart: sms-app-0.1.0
    app.kubernetes.io/name: sms-app
    app.kubernetes.io/instance: sms-app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      app.kubernetes.io/name: sms-app
      app.kubernetes.io/instance: sms-app
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/name: sms-app
        app.kubernetes.io/instance: sms-app
    spec:
      containers:
      - name: frontend
        image: "ghcr.io/doda25-team23/app:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: MODEL_HOST
          value: "http://sms-app-model-service:8081"
        envFrom:
        - configMapRef:
            name: sms-app-config
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
---
# Source: sms-app/templates/model-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-app-model-service
  namespace: sms-app
  labels:
    helm.sh/chart: sms-app-0.1.0
    app.kubernetes.io/name: sms-app
    app.kubernetes.io/instance: sms-app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    app: model-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model-service
      app.kubernetes.io/name: sms-app
      app.kubernetes.io/instance: sms-app
  template:
    metadata:
      labels:
        app: model-service
        app.kubernetes.io/name: sms-app
        app.kubernetes.io/instance: sms-app
    spec:
      containers:
      - name: model-service
        image: "ghcr.io/doda25-team23/model-service:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        volumeMounts:
        - name: shared-storage
          mountPath: /app/shared
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /apidocs
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /apidocs
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: shared-storage
        hostPath:
          path: /mnt/shared
          type: DirectoryOrCreate
---
# Source: sms-app/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sms-app-ingress
  namespace: sms-app
  labels:
    helm.sh/chart: sms-app-0.1.0
    app.kubernetes.io/name: sms-app
    app.kubernetes.io/instance: sms-app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: app.sms-detector.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sms-app-frontend
            port:
              number: 8080
