apiVersion: v2
name: sms-app
description: SMS Spam Detection Application - Helm Chart
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - sms
  - spam-detection
  - machine-learning
maintainers:
  - name: DODA25-Team23
